#!/usr/bin/env bash
# Function to get and display information about a subdomain

subdomain_info() {
    result=$(dig +short "$2.$1" | grep '^[0-9]')
    if [ -n "$result" ]; then
        record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/ {getline; print $4}')
        dest=$(dig +short "$2.$1")
        echo "The subdomain $2 is a $record_type record and points to $dest"
    else
        echo "No records found for the subdomain $2"
    fi
}

if [ $# -eq 1 ]; then
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for sub_domain in "${default_subdomains[@]}"; do
        subdomain_info "$1" "$sub_domain"
    done
elif [ $# -eq 2 ]; then
    subdomain_info "$1" "$2"
else
    echo "Usage: $0 domain [subdomain]"
fi
