#!/usr/bin/env bash
# Bash script that transfers file from client to server

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"
fi