#!/usr/bin/env bash
# Install nginx server

sudo apt-get update

sudo apt-get -y install nginx

#check if web dir is there
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start